"""Ingestion constants, path anchors, metadata key lists, and model limits.

Author: deviprasad
"""
from __future__ import annotations

from pathlib import Path

# ``ingest/`` package root (this file lives in ``ingest/core/``).
PACKAGE_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = PACKAGE_DIR.parent
SCRIPT_DIR = REPO_ROOT

INGESTION_VERSION = "2.0"
MAX_RETRIES = 5
EMBED_BACKOFF_SEC = 5

METADATA_KEYS = [
    "source",
    "source_type",
    "domain",
    "repository",
    "relative_path",
    "extension",
    "file_size_kb",
    "last_modified",
    "chunk_strategy",
    "chunk_type",
    "chunk_name",
    "chunk_index",
    "section",
    "subsection",
    "content_type",
    "concepts",
    "ingestion_date",
    "ingestion_version",
    "rfc_number",
    "rfc_title",
    "section_number",
    "section_title",
    "fsm_state",
    "fsm_event",
    "fsm_state_header",
    "fsm_event_raw",
    "fsm_illegal",
    "fsm_parse_error",
    "rfc_topics",
    "rfc_stack_layer",
    "rfc_profile_title",
    "contains_diagram",
    "diagram_type",
    "rally_id",
    "ticket_id",
    "mib_module",
    "oid_path",
    "page_title",
    "space",
    "labels",
    "author",
    "parent_page",
    "page_url",
    "version",
    "release_date",
    "section_category",
    "artifact_type",
    "state",
    "priority",
    "iteration",
    "release",
    "created_date",
    "closed_date",
    "tags",
    "customer_type",
    "product_version",
    "related_rally",
    "syntax",
    "max_access",
    "status",
    "object_type",
    "source_platform",
    "source_url",
    "is_resolved",
    "has_resolution",
    "has_workaround",
    "severity",
    "quality_score",
    "doc_title",
    "object_name",
    "context_window",
    "dependencies",
    "c_requires_network_byte_order",
    "c_byte_alignment_warning",
    "rfc_dependencies",
    "hierarchical_path",
    "hierarchical_field",
    "layer",
    "protocol_name",
]

CONTENT_TYPE_SIGNALS = {
    "edge_case": [
        "edge case",
        "workaround",
        "gotcha",
        "corner case",
        "fails when",
        "breaks when",
        "known issue",
        "known bug",
        "unexpected",
        "pitfall",
    ],
    "algorithm": [
        "algorithm",
        "how it works",
        "process",
        "steps",
        "flow",
        "procedure",
        "computes",
        "iterates",
        "pseudocode",
    ],
    "rationale": [
        "the reason why",
        "that's why we",
        "rationale",
        "design decision",
        "trade-off",
        "tradeoff",
        "motivation for",
        "we chose",
        "was chosen because",
        "instead of",
        "the thinking behind",
        "decided to",
    ],
    "glossary": [
        "glossary",
        "definition",
        "terminology",
        "is defined as",
        "refers to",
    ],
    "interaction": [
        "depends on",
        "feeds into",
        "consumed by",
        "upstream",
        "downstream",
        "triggered by",
        "interface",
        "contract",
    ],
    "constraint": [
        "assumption",
        "constraint",
        "limitation",
        "prerequisite",
        "must be",
        "cannot",
        "restricted",
        "only works",
    ],
    "bug_report": [
        "bug",
        "defect",
        "regression",
        "crash",
        "root cause",
        "steps to reproduce",
        "reproduc",
    ],
    "workaround": ["workaround", "temporary fix", "mitigation", "until fixed"],
    "howto": [
        "how to",
        "tutorial",
        "step by step",
        "getting started",
        "example",
    ],
    "api": [
        "api",
        "function signature",
        "parameters",
        "returns",
        "class reference",
    ],
}

# Target max tokens per chunk for RFC splitting (char budget ~= tokens * 4).
MODEL_TOKEN_LIMITS = {
    "mxbai-embed-large": 512,
    "nomic-embed-text": 8192,
}
DEFAULT_RFC_TOKEN_LIMIT = 512

STRATEGY_SIZE_LIMIT_MB = {
    "code": 5,
    "domain_doc": 10,
    "theory": 20,
    "config": 2,
    "mib": 5,
    "ticket": 5,
    "rfc": 2,
    "release_notes": 10,
    "community": 5,
    "wiki": 10,
    "default": 5,
}

MIB_MODULE_CONCEPTS = {
    "BRIDGE-MIB": "stp,forwarding_table",
    "IF-MIB": "interface_management",
    "Q-BRIDGE-MIB": "vlan",
    "LLDP-MIB": "lldp",
}

# Config / data files (plan: 2 MB cap when ingested as code)
CONFIG_EXTS = {".json", ".yaml", ".yml", ".toml", ".ini", ".cfg", ".conf", ".properties", ".xml"}

# Code-mode traversal: skip VCS, deps, build outputs, and common binaries
IGNORED_DIRS = {
    ".git",
    ".svn",
    ".hg",
    "node_modules",
    "build",
    "dist",
    "target",
    "__pycache__",
    "bin",
    "obj",
    "vendor",
    ".idea",
    ".vs",
    ".vscode",
    ".venv",
    "venv",
    ".tox",
    ".eggs",
    ".mypy_cache",
    ".pytest_cache",
    "CMakeFiles",
    "Debug",
    "Release",
    "x64",
    "x86",
}

IGNORED_EXTS = {
    ".exe",
    ".dll",
    ".so",
    ".o",
    ".a",
    ".lib",
    ".class",
    ".jar",
    ".zip",
    ".tar",
    ".gz",
    ".7z",
    ".rar",
    ".bz2",
    ".xz",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".svg",
    ".ico",
    ".webp",
    ".bmp",
    ".pdf",
    ".bin",
    ".wasm",
    ".lock",
    ".pyc",
    ".pyo",
    ".pdb",
    ".woff",
    ".woff2",
    ".ttf",
    ".eot",
    ".map",
    ".mp3",
    ".mp4",
    ".avi",
    ".mov",
    ".wmv",
    ".db",
    ".sqlite",
    ".sqlite3",
}

# Sentinel for writer thread shutdown (ingest_job writer loop).
WRITER_STOP = object()
